### ISSUE TITLE
macOS permission denied: ./vulkan_samples.app

### ISSUE THREAD

**Issue by rgosens2** [KhronosGroup/Vulkan-Samples#1069] opened 2024-06-12 19:34 UTC
Builds fine but cannot run app:

zsh: permission denied: ./vulkan_samples.app

Running from Contents:

./vulkan_samples sample hello_triangle

[info] Logger initialized
[info] Initializing vulkan instance.
[info] Enabled Validation Layers:
[info] Found GPU: Apple M1
[info] Initializing vulkan device.
[error] Error Message: Failed to open file for reading
[error] Failed when running application hello_triangle

**Comment by jeroenbakker-atmind** [comment] 2024-07-01 15:39
According to the docs you need to run it from the root of the repository to locate the assets it needs. Also the .app isn't the executable, but the container. Have you tried:

```
/build/mac/app/bin/Debug/arm64/vulkan_samples.app/Contents/MacOS/vulkan_samples sample hello_triangle
```

**Comment by marty-johnson59** [comment] 2024-07-15 16:51
Hi @rgosens2, can you check if this fixes your problem - and close this issue if so?  Thanks!

**Comment by jeroenbakker-atmind** [comment] 2024-08-20 19:21
I'll close the issue. Please reopen when the issue isn't fixed. Thanks!

**Closed as completed by jeroenbakker-atmind** 2024-08-20 19:21 UTC
Labels: Mac
