### ISSUE TITLE
Android Gradle build error (Linux host): `Expected output file at [...]/hdr for target hdr but there was none`

### ISSUE THREAD

**Issue by hevrard** [KhronosGroup/Vulkan-Samples#18] opened 2019-11-27 11:41 UTC
Host: Linux x64 (debian-testing based)
Gradle version: 5.1.1
CMake: 3.13.4

The command `./gradlew assembleDebug` fails with:

```
[...]
[12/12] Linking CXX executable third_party/spirv-cross/bin/Debug/armeabi-v7a/spirv-cross
Build instancing armeabi-v7a
ninja: no work to do.
Build push_descriptors armeabi-v7a
ninja: no work to do.
Build afbc armeabi-v7a
ninja: no work to do.
Build terrain_tessellation armeabi-v7a
ninja: no work to do.
Build hello_triangle armeabi-v7a
ninja: no work to do.
Build hdr armeabi-v7a
ninja: no work to do.

> Task :externalNativeBuildDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':externalNativeBuildDebug'.
> Expected output file at /home/hevrard/work/Vulkan-Samples/build/android_gradle/build-native/cmake/debug/armeabi-v7a/samples/api/hdr/hdr for target hdr but there was none
```

Getting rid of "armeabi-v7a" in `build.gradle`'s ndk abiFilters leads to a similar error :

```
Execution failed for task ':externalNativeBuildDebug'.
> Expected output file at /home/hevrard/work/Vulkan-Samples/build/android_gradle/build-native/cmake/debug/arm64-v8a/samples/performance/command_buffer_usage/command_buffer_usage for target command_buffer_usage but there was none
```

**Comment by solidpixel** [comment] 2019-12-03 10:24
Hit the same problem on the following config:

* Host: Windows 10
* Gradle 5.6.4
* CMake 3.16.0

**Comment by solidpixel** [comment] 2019-12-03 10:57
With some digging - this looks to be a compatibility issue with newer versions of CMake. Using the 3.10.2 version which is referenced in the code works OK.

**Comment by hevrard** [comment] 2019-12-03 17:33
Confirmed that it works for me on Linux with cmake 3.10.2. Thanks @solidpixel !

**Comment by ryanoshea-arm** [comment] 2019-12-06 11:43
Hi @hevrard 

Did you have the ANDROID_HOME environment variable set when you ran the `./gradle assembleDebug` command?

**Comment by hevrard** [comment] 2019-12-06 12:30
> Did you have the ANDROID_HOME environment variable set when you ran the `./gradle assembleDebug` command?

Yes.

I try to have all combinations defined:
```
ANDROID_HOME=$HOME/android-sdk
ANDROID_SDK=$HOME/android-sdk
ANDROID_SDK_HOME=$HOME/android-sdk
ANDROID_NDK=$HOME/android-sdk/ndk-bundle
ANDROID_NDK_HOME=$HOME/android-sdk/ndk-bundle
ANDROID_NDK_ROOT=$HOME/android-sdk/ndk-bundle
```

**Comment by ryanoshea-arm** [comment] 2019-12-06 14:19
Does the build still fail if you have a local.properties file which includes the path to the Android SDK within the android_gradle directory?

**Comment by hevrard** [comment] 2019-12-06 16:57
> Does the build still fail if you have a local.properties file which includes the path to the Android SDK within the android_gradle directory?

I don't have time to try this right now, but note that the build works with cmake 3.10.2. See #21 

Do you still need/want to debug issues with more recent cmake?

**Comment by ryanoshea-arm** [comment] 2019-12-10 13:11
If the issue is now solved for you then I believe we can close this issue, thanks for reporting it!

**Comment by hevrard** [comment] 2019-12-10 13:28
@ryanoshea-arm I was waiting for someone to review #21, such that merging this PR would close this issue automatically. Can you have a look? (I cannot put new assignee on the PR as I don't have enough  access rights to this repo I guess)

**Closed as completed** 2019-12-13 11:53 UTC
